### ISSUE TITLE
Codable with date encoding / decoding strategy

### ISSUE THREAD

**Issue by thang-nm** [intelygenz/NetClient-iOS#18]
How can i add date encoding / decoding strategy to response.decode()?

**Comment by alexruperez** [comment]
@Lang-le, can you tell us how do you finally fix this issue please? Thanks! 🙂

**Comment by thang-nm** [comment]
@alexruperez, I decode manually from response?.object()
```
let decoder = JSONDecoder()
decoder.dateDecodingStrategy = .formatted(myDateFormatter)
if let data: Data = try response?.object(),
    let json: MyClass = try? decoder.decode(MyClass.self, from: data) {
  // do something
}

**Comment by alexruperez** [comment]
Ok @Lang-le, I'll try to integrate dateDecodingStrategy in the decode() method, reopening the issue, thanks for the feedback! 🙌

**Comment by alexruperez** [comment]
Working @Lang-le, thanks again!
